import img from "./assets/pdf_img.png"
import formimg from "../src/form_img.png";
import user_img from "../src/profile_img_default.png";

const formsData = [
  {
    id: 1,
    image: formimg,
    esbh_hole_no: null,
    address:
      "Spire of Dublin, O'Connell Street Upper, North City, Dublin, Ireland",
    coordinates: "53.3498114 -6.2602525",
    length: 1,
    width: 2,
    area: 2,
    surface_category: "granite slabs",
    reinstatement: "Permanent",
    status: "In progress",
    comments: ["No comment", "Nothing to say"],
    date: "01/01/2023",
  },
  {
    id: 2,
    image: formimg,
    address:
      "Spire of Dublin, O'Connell Street Upper, North City, Dublin, Ireland",
    coordinates: "53.3498114 -6.2602525",
    length: 1,
    width: 2,
    area: 2,
    surface_category: "granite slabs",
    reinstatement: "Permanent",
    status: "Completed",
    comments: [
      "No comment",
      "The two basic components required to load a simple map are: LoadScript - Loads the Google Maps API script GoogleMap - The map component inside which all other components renderThe simplest way to get a functional map is:Make sure you cache the props passed to GoogleMap to avoid re-renders that may harm the performance. to say",
    ],
    date: "01/01/2023",
  },
  {
    id: 3,
    image: formimg,
    address:
      "Spire of Dublin, O'Connell Street Upper, North City, Dublin, Ireland",
    coordinates: "53.3498114 -6.2602525",
    length: 1,
    width: 2,
    area: 2,
    surface_category: "granite slabs",
    reinstatement: "Permanent",
    status: "Completed",
    comments: [
      "No comment",
      "The two basic components required to load a simple map are: LoadScript - Loads the Google Maps API script GoogleMap - The map component inside which all other components renderThe simplest way to get a functional map is:Make sure you cache the props passed to GoogleMap to avoid re-renders that may harm the performance. to say",
    ],
    date: "07/01/2023",
  },
];

const pdfsData = [
  {
    id: 1,
    type: "Hole",
    image: img,
    esbh_hole_no: 123,
    local_authority_licence_number: 456,
    traffic_impact_number: 789,
    name: "PDF",
    date: "02/01/2023",
    address: "Dublin 01",
    holes: [formsData[0], formsData[1]],
    final_file_attached: "attached",
    pdf_sections_completed: 3,
    last_updated_by: "Gian",
  },
  {
    id: 2,
    type: "Hole",
    image: img,
    esbh_hole_no: 123,
    local_authority_licence_number: 456,
    traffic_impact_number: 789,
    name: "PDF made by the Admin",
    date: "01/01/2023",
    address: "Dublin 01",
    holes: [formsData[0]],
    final_file_attached: null,
    pdf_sections_completed: 4,
    last_updated_by: "Gian",
  },
  {
    id: 3,
    type: "Hole",
    image: img,
    esbh_hole_no: 123,
    local_authority_licence_number: 456,
    traffic_impact_number: 789,
    name: "PDF made by the Admin",
    date: "01/01/2023",
    address: "Dublin 01",
    holes: [formsData[0]],
    final_file_attached: "attached",
    last_updated_by: "Giannn",
  },
  {
    id: 4,
    type: "Hole",
    image: img,
    esbh_hole_no: 123,
    local_authority_licence_number: 456,
    traffic_impact_number: 789,
    name: "PDF made by the Admin",
    date: "01/01/2023",
    address: "Dublin 01",
    holes: [formsData[0]],
    final_file_attached: null,
    last_updated_by: "Gian",
  },
  {
    id: 5,
    type: "Hole",
    image: img,
    esbh_hole_no: 123,
    local_authority_licence_number: 456,
    traffic_impact_number: 789,
    name: "PDF made by the Admin",
    date: "01/01/2023",
    address: "Dublin 01",
    holes: [formsData[0]],
    final_file_attached: null,
    last_updated_by: "Gian",
  },
  {
    id: 6,
    type: "Hole",
    image: img,
    esbh_hole_no: 123,
    local_authority_licence_number: 456,
    traffic_impact_number: 789,
    name: "PDF made by the Admin",
    date: "01/01/2023",
    address: "Dublin 01",
    holes: [formsData[0]],
    final_file_attached: null,
    last_updated_by: "Gian",
  },
  {
    id: 7,
    type: "Hole",
    image: img,
    esbh_hole_no: null,
    local_authority_licence_number: 456,
    traffic_impact_number: 789,
    name: "PDF made by the Admin",
    date: "01/01/2023",
    address: "Dublin 01",
    holes: [formsData[0]],
    final_file_attached: null,
    last_updated_by: "Gian",
  },
];

const users_staff = [
  {
    id: 1,
    name: "Gian Valentim",
    image: user_img,
    email: "gian@s.com",
    phone: "123 456 45",
    isadmin: false,
    role: "Engineer",
  },
  {
    id: 2,
    name: "Gian",
    image: user_img,
    email: "gian@s.com",
    phone: "123 456 45",
    isadmin: false,
    role: "Engineer",
  },
  {
    id: 3,
    name: "Gian",
    image: user_img,
    email: "gian@s.com",
    phone: "123 456 45",
    isadmin: true,
    role: "Engineer",
  },
  {
    id: 4,
    name: "Gian",
    image: user_img,
    email: "gian@s.com",
    phone: "123 456 45",
    isadmin: true,
    role: "Engineer",
  },
];

export { pdfsData, users_staff, formsData };
